creation_rules:
  - path_regex: \.(env|env\.enc)$
    age: >-
      age18qxsdc2cg390cudnaf9h7njcx2kcqjte07vfs37dy6xldp7f3v8qgmvqrk,
      age1dfptqgyefhqjjednnjs5szfafzmk0hs23u85g6h7n2uajgtae3lquhkzs7
    input_type: dotenv
    output_type: dotenv
