alias VIDEO='cd /mnt/sdcard/video' # переходим в папку video
alias mos='cd /mnt/sdcard/mos' # переходим в папку mos
alias CODDING='cd /mnt/sdcard/video/CODDING' # переходим в папку video
alias FRONT='cd /mnt/sdcard/video/FRONT' # переNavig в папку FRONT
alias HTML='cd /mnt/sdcard/video/FRONT/html' # переNavig в папку FRONT
alias html='cd /mnt/sdcard/github/html' # переNavig в папку FRONT
alias github='cd /mnt/sdcard/github' # переходим в папку github
alias dslibs='cd /mnt/sdcard/dslibs' # переходим в папку github
alias DSLIBS='cd /mnt/sdcard/video/DSLIBS' # переходим в папку github
alias ubuntu='cd /mnt/sdcard/github/ubuntu' # переходим в папку github
alias DS='cd /mnt/sdcard/video/AI/DS' # переходим в папку video
alias ds='cd /mnt/sdcard/github/ds' # переходим в папку github
alias AI='cd /mnt/sdcard/video/AI' # переходим в папку video
alias c2='cd /mnt/sdcard/github/c2' # переходим в папку video
alias ciot='cd /mnt/sdcard/github/ciot' # переходим в папку video
alias MATH='cd /mnt/sdcard/video/AI/Math/' # переходим в папку video
alias math='cd /mnt/sdcard/github/math' # переходим в папку video
alias dslibs='cd /mnt/sdcard/github/dslibs' # переходим в папку video
alias DSLIBS='cd /mnt/sdcard/video/AI/dslibs' # переходим в папку video
alias ubuntu='cd /mnt/sdcard/github/ubuntu' # переNavig в папку github
alias js='cd /mnt/sdcard/github/js' # переNavig в папку github
alias hh='cd /mnt/sdcard/github/hh' # переNavig в папку github
alias dipiot='cd /mnt/sdcard/github/dipiot' # переNavig в папку github
alias dipai='cd /mnt/sdcard/github/dipai' # переNavig в папку github
alias JS='cd /mnt/sdcard/video/FRONT/js' # переNavig в папку FRONT
alias ADJS='cd /mnt/sdcard/video/FRONT/adjs' # переNavig в папку FRONT
alias adjs='cd /mnt/sdcard/github/adjs' # переходим в папку video
alias dls='cd /mnt/sdcard/github/dls' # переходим в папку video
alias Downloads='cd /mnt/sdcard/Downloads' #  в папку Загрузки
alias sbin='cd /usr/local/sbin' #  в папку sbin
alias MATAN='cd /mnt/sdcard/video/AI/Matan/' # переходим в папку video
alias matan='cd /mnt/sdcard/github/matan' # переходим в папку video
alias algo='cd /mnt/sdcard/github/algo' # переходим в папку video
alias ALGO='cd /mnt/sdcard/video/DS/algo' # переходим в папку video
alias ECMA='cd /mnt/sdcard/video/FRONT/ecma' # переходим в папку video
alias ecma='cd /mnt/sdcard/github/ecma' # переходим в папку video
alias start='cd /mnt/sdcard/github/start' # переходим в папку video
alias life='cd /mnt/sdcard/video/PRODUCT/life' # переходим в папку video
alias NODEJS='cd /mnt/sdcard/video/FRONT/node' # переходим в папку video
alias nodejs='cd /mnt/sdcard/github/node' # переходим в папку video
alias react='cd /mnt/sdcard/github/react' # переходим в папку video
alias REACT='cd /mnt/sdcard/video/FRONT/react' # переходим в папку video
alias adhtml='cd /mnt/sdcard/github/adhtml' # переходим в папку video
alias WINDOW='cd /mnt/sdcard/video/FRONT/window' # переходим в папку video
alias window='cd /mnt/sdcard/github/window' # переходим в папку video
alias base.php='cd /mnt/sdcard/github/base.php' # переходим в папку video
alias itreact='cd /mnt/sdcard/github/itreact' # переходим в папку video
alias lureact='cd /mnt/sdcard/github/lureact' # переходим в папку video
alias itshop='cd /mnt/sdcard/github/itshop' # переходим в папку video
alias Flask='cd /mnt/sdcard/github/flask' # переходим в папку video
alias FLASK='cd /mnt/sdcard/video/PYTHON/Flask' # переходим в папку video
alias reactm='cd /mnt/sdcard/github/reactm' # переNavig в папку FRONT
alias REACTM='cd "/mnt/sdcard/video/STEPIK/React - Полное руководство 2023"' # переNavig в папку FRONT
alias cicd='cd /mnt/sdcard/gitlab/cicd' # переNavig в папку в гитлабе CICD
alias gitlab='cd /mnt/sdcard/gitlab/' # переNavig в папку в гитлабе CICD
alias focus='cd /mnt/sdcard/focus' # переходим в папку video
alias FastAPI='cd /mnt/sdcard/github/fastapi' # переходим в папку video
alias webserial='cd /mnt/sdcard/github/webserial' # переходим в папку video
alias backend='cd /mnt/sdcard/focus/backend' # переходим в папку backend
alias variables='cd /mnt/sdcard/focus/management/variables' # переходим в папку backend
alias nginx='cd /mnt/sdcard/focus/management/nginx' # переходим в папку backend
alias gitlab-profile='cd /mnt/sdcard/focus/gitlab-profile' # переходим в папку backend
alias webserial='cd /mnt/sdcard/github/webserial' # переходим в папку video
alias eloquent='cd /mnt/sdcard/github/eloquent' # переходим в папку video
alias graph='cd /mnt/sdcard/github/graph' # переходим в папку video
alias frontend='cd /mnt/sdcard/focus/frontend' # переходим в папку video
alias admin='cd /mnt/sdcard/github/admin' # переходим в папку admin
alias onedrive='cd /mnt/sdcard/cloud/allseen'
alias mos='cd /mnt/sdcard/mos'
alias shur='cd /mnt/sdcard/mos/shur'
alias usb='cd /mnt/sdcard/github/usb' # переходим в папку usb
alias pythondive='cd /mnt/sdcard/github/pythondive' # переходим в папку pythondive
